### ISSUE TITLE
mysql_* not supported in php7

### ISSUE THREAD

**Issue by alvarofblanco** [mosky17/club-cannabico-aecu#1]
Estoy teniendo muchos problemas para implementar este software y todo apunta a que se hizo en php5 y php7 es la version estable.
Hay planes de actualizar?

**Comment by mosky17** [comment]
Hola Alvaro, de a poco he ido cambiando alguna cosa en la versión que tenemos en uso nosotros, pero no esta hecha toda la migración.

Seguramente lo único que hay que hacer es cambiar todas las llamadas de mysql_* a la nueva sintaxis.

Dejame ver si te puedo subir algún cambio. como solución rapida, lo que podes hacer es tratar de buscar un hosting con php viejo.
